### ISSUE TITLE
In an HTML generated by @kolkov/angular-editor every break line looses one word

### ISSUE THREAD

**Issue by BlackRoadCode** [nerdmax/word-counting#52]
# Prerequisites

- [X ] Can you reproduce the problem in safe mode?
- [ X] Are you running the latest version?
- [ X] Did you check the FAQs on Discuss?
- [ X] Are you reporting to the correct repository?
- [ ] Did you perform a cursory search?

# Description

hi I'm trying to count the words of the HTML generated from In an HTML generated by @ kolkov / angular-editor and I noticed that every time I give enter to generate a new line, the counter loses a word (the first one) in the second starts counting again.

- **I'm submitting a ...**

  - [ X] bug report

- **What is the current behavior?**
loses a word (the first one) in the second starts counting again.

- **What is the expected behavior?**
count all the words in the html

- **Please tell us about your environment:**

dependencies: 
```
import { AngularEditorConfig } from '@kolkov/angular-editor';
import wordsCounter from 'word-counting'
```

in HTML 

`<angular-editor [(ngModel)]="htmlContent" [config]="config" (ngModelChange)="countingWords($event)"></angular-editor>`

in TS file

```
countingWords( event ):number{
     return this.wordCount = wordsCounter(event, { isHtml: true }).wordsCount;
   };
```

  - Version: [ 1.1.3 ]
  - Environment:
    - Browser: [ Chrome XX | Opera GX]
    - Node: [ 14.15.1 ]
  - Language: [ TypeScript X.X]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![bien](https://user-images.githubusercontent.com/67574498/107157637-c5aedd80-694a-11eb-8a7d-110ea248b9ed.PNG)
![mal1](https://user-images.githubusercontent.com/67574498/107157638-c5aedd80-694a-11eb-892c-387edd8ef8c9.PNG)
![mal2](https://user-images.githubusercontent.com/67574498/107157639-c6477400-694a-11eb-8ec8-1d7aa4148aa2.PNG)

**Comment by nerdmax** [comment]
@BlackRoadCode Sorry I didn't notice this issue report a year ago. Now it has been fixed on version@1.1.4. Thank you for reporting the issue!
